"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Server, ArrowRight, LogOut } from "lucide-react";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
type Guild = { id: string; name: string; icon: string | null; botPresent: boolean };
export default function GuildsPage() { const [guilds, setGuilds] = useState<Guild[]>([]); const [error, setError] = useState("");
  useEffect(() => { fetch(`${api}/api/guilds`, { credentials: "include" }).then(async response => { if (!response.ok) throw new Error("Please sign in again."); return response.json(); }).then(data => setGuilds(data.guilds)).catch(e => setError(e.message)); }, []);
  return <main className="shell min-h-screen px-6 py-10 md:px-12"><header className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="accent text-sm uppercase tracking-[.25em]">Control Room</p><h1 className="mt-2 text-4xl">Choose a server</h1></div><button onClick={() => fetch(`${api}/api/auth/logout`, { method: "POST", credentials: "include" }).then(() => location.assign("/"))} className="flex items-center gap-2 text-sm text-slate-400 hover:text-white"><LogOut size={16}/> Sign out</button></header><section className="mx-auto mt-12 grid max-w-6xl gap-4 md:grid-cols-2 lg:grid-cols-3">{error && <p className="text-rose-300">{error}</p>}{guilds.map(guild => <article key={guild.id} className="glass rounded-2xl p-5 transition hover:-translate-y-1 hover:border-[#7cf7c8]/50"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#1e293b] text-[#7cf7c8]"><Server size={22}/></div><div className="min-w-0"><h2 className="truncate text-xl">{guild.name}</h2><p className="text-xs text-slate-500">{guild.botPresent ? "Bot connected" : "Bot not connected"}</p></div></div>{guild.botPresent ? <Link href={`/dashboard/${guild.id}`} className="mt-6 flex items-center justify-between rounded-xl border border-[#243047] px-4 py-3 text-sm hover:border-[#7cf7c8]"><span>Manage server</span><ArrowRight size={16}/></Link> : <a href={`https://discord.com/oauth2/authorize?client_id=${process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID ?? ""}&scope=bot%20applications.commands&permissions=8&guild_id=${guild.id}`} className="mt-6 flex items-center justify-between rounded-xl bg-[#7cf7c8] px-4 py-3 text-sm font-bold text-[#0b0f19]"><span>Invite bot</span><ArrowRight size={16}/></a>}</article>)}</section></main>; }
